#!/bin/sh
if [ -x /usr/bin/python2 ]; then
	python2 /usr/bin/twistd --nodaemon --python loginserver.tac --pidfile loginserver.pid
elif [ -x /usr/bin/python2.7 ]; then
        python2.7 /usr/bin/twistd --nodaemon --python loginserver.tac --pidfile loginserver.pid
else
	python /usr/bin/twistd --nodaemon --python loginserver.tac --pidfile loginserver.pid
fi
