LIGHTLEVEL_NONE = 0
LIGHTLEVEL_TORCH = 7
LIGHTLEVEL_FULL = 27
LIGHTLEVEL_WORLD = 255

LIGHTCOLOR_NONE = 0
LIGHTCOLOR_DEFAULT = 206 # Orange
LIGHTCOLOR_WHITE = 215

SLOT_WHEREEVER = 0
SLOT_FIRST = 1
SLOT_HEAD = SLOT_FIRST
SLOT_NECKLACE = 2
SLOT_BACKPACK = 3
SLOT_ARMOR = 4
SLOT_RIGHT = 5
SLOT_LEFT = 6
SLOT_LEGS = 7
SLOT_FEET = 8
SLOT_RING = 9
SLOT_AMMO = 10
SLOT_DEPOT = 11
SLOT_LAST = SLOT_DEPOT
SLOT_HAND = 12
SLOT_TWO_HAND = 12
